"""Golden-target triage: rank live hosts by how promising they are to test.

Ported from the original recon pipeline (module 2). Each host gets signals
from its probe results and a score:

  AUTH     401, or 403 that is not a WAF block page      +4
  TITLE    title looks like a login/admin/console page   +4
  APPTECH  application technology beyond CDN/edge noise   +2
  ODDPORT  web service on a port other than 80/443        +1
  KEYWORD  host name matches the golden keyword list      +1
  200      at least one 200 response                      +1
  WAF      title looks like a WAF/bot challenge page      (flag only)
"""
import re

GOLDEN_KEYWORDS = (r"admin|api|dev|uat|test|stg|portal|dashboard|login|payment|upload|extranet|"
                   r"sso|b2b|erp|sap|shop|account")

_TITLE = re.compile(r"login|sign[ -]?in|admin|portal|dashboard|swagger|graphql|jenkins|grafana|kibana|"
                    r"gitlab|jira|confluence|storybook|phpmyadmin|console|webmail|roundcube|sonarqube|"
                    r"airflow|kubernetes|rancher", re.I)
_WAF = re.compile(r"attention required|just a moment|blocked by our firewall|access denied|waf block|"
                  r"hello there, human|cloudflare|request could not be satisfied|generated by cloudfront|"
                  r"akamai|access to this page has been denied|incapsula|request blocked|error 10\d\d|"
                  r"bot detect", re.I)
_BORING = re.compile(r"^(amazoncloudfront|amazonelb|amazonwebservices|awselb|envoy|hsts|googlecloud|"
                     r"googlecloudcdn|googlefontapi|googlehostedlibraries|googletagmanager|microsofthttpapi|"
                     r"cloudflare|akamai|fastly|varnish|http/[0-9.]+|.*bot management|.*browser insights|"
                     r".*radar|amazon.*|google.*|sucuri|imperva|incapsula|f5 big-?ip|open-?resty|ipv6|dns|"
                     r"acme|lets? ?encrypt)$", re.I)

WEIGHTS = {"AUTH": 4, "TITLE": 4, "APPTECH": 2, "ODDPORT": 1, "KEYWORD": 1, "200": 1}
GOLDEN_MIN_SCORE = 4


def _tech_name(t: str) -> str:
    # httpx reports "Nginx:1.27.5"; compare on the name only, lower-cased, no spaces.
    return t.split(":")[0].strip().lower().replace(" ", "")


def score_host(host: str, probes: list[dict], keywords: str = GOLDEN_KEYWORDS) -> dict:
    """probes: one dict per (scheme, port) probe of this host with status_code/title/tech/port."""
    statuses = {str(p["status_code"]) for p in probes if p.get("status_code")}
    titles = [p["title"].strip() for p in probes if (p.get("title") or "").strip()]
    tech = list(dict.fromkeys(t for p in probes for t in (p.get("tech") or [])))
    ports = {str(p.get("port")) for p in probes if p.get("port")}
    title_all = " / ".join(titles)
    waf = bool(title_all and _WAF.search(title_all))

    sig = []
    if "401" in statuses or ("403" in statuses and not waf):
        sig.append("AUTH")
    if waf:
        sig.append("WAF")
    if title_all and _TITLE.search(title_all):
        sig.append("TITLE")
    if any(not _BORING.match(_tech_name(t)) for t in tech):
        sig.append("APPTECH")
    if ports - {"80", "443"}:
        sig.append("ODDPORT")
    if re.search(keywords, host, re.I):
        sig.append("KEYWORD")
    if "200" in statuses:
        sig.append("200")

    score = sum(WEIGHTS.get(s, 0) for s in sig)
    return {"host": host, "score": score, "signals": sig, "golden": score >= GOLDEN_MIN_SCORE,
            "statuses": sorted(statuses), "ports": sorted(ports), "titles": titles[:3], "tech": tech[:8]}


def rank(probes_by_host: dict[str, list[dict]], keywords: str = GOLDEN_KEYWORDS) -> list[dict]:
    rows = [score_host(h, p, keywords) for h, p in probes_by_host.items() if p]
    rows.sort(key=lambda r: (-r["score"], r["host"]))
    return rows
