#!/usr/bin/env bash
# Build the public verifier page, site/verify.html (attackledger.com/verify), from
# web/src/verify_page.html and web/src/verify_page.ts. The page is one self-contained file:
# its script (web/src/verify_report.ts, the same module the app's Verify tab uses), its
# fonts and the pinned timestamp roots are inline, and its Content-Security-Policy, in a
# meta tag and in tools/build_pages.sh's _headers, allows no connection at all.
#
# Also writes web/src/tsa_roots.ts from tools/tsa-roots/*.pem, so the page and the app trust
# exactly the roots verify_report.py trusts by default.
# Needs web/node_modules (cd web && npm ci). Usage: tools/build_verify.sh
set -euo pipefail
cd "$(dirname "$0")/.."
ESBUILD=web/node_modules/.bin/esbuild
[ -x "$ESBUILD" ] || { echo "run 'cd web && npm ci' first (esbuild comes with vite)" >&2; exit 1; }

python3 -I - <<'PY'
import json, pathlib
roots = sorted(pathlib.Path("tools/tsa-roots").glob("*.pem"))
rows = "\n".join(f"  {{ name: {json.dumps(p.name)}, text: {json.dumps(p.read_text(encoding='ascii'))} }},"
                 for p in roots)
pathlib.Path("web/src/tsa_roots.ts").write_text(
    "// Generated by tools/build_verify.sh from tools/tsa-roots/*.pem; do not edit by hand. The\n"
    "// verifier page and the app's Verify tab trust exactly the roots verify_report.py trusts by default.\n"
    f"export const TSA_ROOTS: {{ name: string; text: string }}[] = [\n{rows}\n];\n")
PY

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT
"$ESBUILD" web/src/verify_page.ts --bundle --format=iife --target=es2020 --charset=utf8 \
  --legal-comments=none --log-level=warning --outfile="$TMP/verify_page.js"

python3 -I - "$TMP/verify_page.js" <<'PY'
import base64, hashlib, pathlib, re, sys
script = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8").strip("\n")
if re.search(r"</script|<!--", script, re.I):
    sys.exit("the bundled script contains </script or <!--, which would break the inline script")
fonts = pathlib.Path("web/node_modules/@fontsource")
faces = []
for family, weight, path in (("Atkinson Hyperlegible", 400, "atkinson-hyperlegible/files/atkinson-hyperlegible-latin-400-normal.woff2"),
                             ("Atkinson Hyperlegible", 700, "atkinson-hyperlegible/files/atkinson-hyperlegible-latin-700-normal.woff2"),
                             ("Zilla Slab", 700, "zilla-slab/files/zilla-slab-latin-700-normal.woff2")):
    data = base64.b64encode((fonts / path).read_bytes()).decode()
    faces.append(f'@font-face {{ font-family: "{family}"; font-style: normal; font-weight: {weight}; font-display: swap; '
                 f'src: url(data:font/woff2;base64,{data}) format("woff2"); }}')
page = pathlib.Path("web/src/verify_page.html").read_text(encoding="utf-8")
style = re.search(r"<style>(.*?)</style>", page, re.S).group(1).replace("/* FONTS */", "\n".join(faces))
page = page.replace(re.search(r"<style>(.*?)</style>", page, re.S).group(1), style, 1)

def digest(text):
    return "'sha256-" + base64.b64encode(hashlib.sha256(text.encode()).digest()).decode() + "'"

csp = "; ".join([
    "default-src 'none'",
    f"script-src {digest(script)}",
    f"style-src {digest(style)}",
    "font-src data:",
    "img-src data:",
    "connect-src 'none'",
    "form-action 'none'",
    "base-uri 'none'",
    "require-trusted-types-for 'script'",
    "trusted-types 'none'",
])
page = page.replace("<!-- CSP -->", f'<meta http-equiv="Content-Security-Policy" content="{csp}">')
page = page.replace("<!-- CSP TEXT -->", csp.replace("&", "&amp;").replace("<", "&lt;"))
page = page.replace("<!-- SCRIPT -->", f"<script>\n{script}\n</script>")
pathlib.Path("site/verify.html").write_text(page, encoding="utf-8")
print(f"site/verify.html: {len(page.encode()) // 1024} KiB, script {len(script.encode()) // 1024} KiB")
PY
