"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 18:01:11.723289
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engagements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pack_id', sa.String(length=64), nullable=False),
    sa.Column('engagement_type', sa.String(length=20), nullable=False),
    sa.Column('policy_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('scope_include', sa.JSON(), nullable=False),
    sa.Column('scope_exclude', sa.JSON(), nullable=False),
    sa.Column('authorized_by', sa.String(length=200), nullable=True),
    sa.Column('authorized_at', sa.DateTime(), nullable=True),
    sa.Column('rate_limit_rps', sa.Integer(), nullable=False),
    sa.Column('research_header', sa.String(length=300), nullable=True),
    sa.Column('research_user_agent', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('in_scope', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id', 'host')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', 'cancelled', name='jobstatus'), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('output_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lanes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'role')
    )
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lane_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('controls', sa.JSON(), nullable=False),
    sa.Column('state', sa.Enum('open', 'done', 'na', name='itemstate'), nullable=False),
    sa.Column('na_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lane_id', sa.Integer(), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engagement_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('chain_hash', sa.String(length=64), nullable=False),
    sa.Column('lane_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('uri', sa.String(length=1000), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['checklist_items.id'], ),
    sa.ForeignKeyConstraint(['lane_id'], ['lanes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engagement_id', 'seq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evidence')
    op.drop_table('receipts')
    op.drop_table('checklist_items')
    op.drop_table('observations')
    op.drop_table('lanes')
    op.drop_table('jobs')
    op.drop_table('assets')
    op.drop_table('engagements')
    # ### end Alembic commands ###
    # Postgres keeps enum types after their tables are dropped.
    bind = op.get_bind()
    sa.Enum(name="jobstatus").drop(bind, checkfirst=True)
    sa.Enum(name="itemstate").drop(bind, checkfirst=True)
