"""lane executor

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-08 19:28:53.668214
"""
from alembic import op
import sqlalchemy as sa


revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lanes', sa.Column('executor', sa.String(length=16), server_default='manual', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lanes', 'executor')
    # ### end Alembic commands ###
